### PR TITLE
Add workflow

### PR DESCRIPTION
**Pull request by nanu-c**

### CODE REVIEW

**Comment by nanu-c** [comment]
Hey @rubdos our ci is failing with pining the version. Lets see why this happens.

**Comment by jonnius** [comment]
You can delete and recreate the Cargo.lock. That should fix it.

**Comment by jonnius** [comment]
And it seems like `libsignal_service` now requires `nightly` features (`encode_to_vec()`)...

**Comment by jonnius** [comment]
Mind #4

**Comment by rubdos** [comment]
> Hey @rubdos our ci is failing with pining the version. Lets see why this happens.

Is this fixed by now? Sounds like the most recent commits broke libsignal-service-actix, I should take a look at that...

**Comment by nanu-c** [comment]
It's fixed now by #4, but we have maybe another artifact which means that the timestamp is 1h off in our timezone. Maybe something changed in that regard.

**Pull request merged**
